let handler = async(m, { conn, text }) => {
  let who = m.mentionedJid[0]
  let kon = m.sender
  let name = conn.getName(m.sender)
  if (!who) return m.reply('```Tag Salah Satu!```')
  let repeat = `
*「  REPEAT TAG  」*

Dari: @${kon.split("@")[0]}
Pesan: ${text ? text : '-'}

🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}
🤣 @${who.split("@")[0]}

*SGDC-BOT*
`.trim()

conn.reply(m.chat, repeat, m, {
           contextInfo: { 
                 mentionedJid: [kon, who]
          } 
      })
  }
  
handler.command = /^(rptag|repeattag)$/i
handler.owner = false
handler.mods = false
handler.premium = true
handler.group = false
handler.private = false

handler.admin = false
handler.botAdmin = false

handler.fail = null


module.exports = handler

//  MUHAMMAD AFDHAN
